### PR TITLE
grimoire mushroom garden

### PR DESCRIPTION
**Pull request by Rinn**
use tearaway pants (can replace with libram shortly)

### CODE REVIEW

**Comment by Rinn** [comment]
```
13:20:12 [92] Your Mushroom Garden
13:20:12 Preference lastEncounter changed from sausage goblin to piranha plant
13:20:12 Encounter: piranha plant
13:20:12 Preference _mushroomGardenFights changed from 0 to 1
13:20:12 Round 0: Rinnith wins initiative!
13:20:12 Preference cosmicBowlingBallReturnCombats changed from 15 to 14
13:20:12 Round 0: Rinnith casts TEAR AWAY YOUR PANTS!!
13:20:12 Round 1: You gain 1 Adventure
13:20:13 You gain 76 Meat.
13:20:13 Preference _tearawayPantsAdvs changed from 0 to 1```

we good

**Comment by ianknowles** [comment]
I'm already swapping my garden at the start of the day in my own scripts. Garbo now exits without an error when trying to swap into the mushroom garden. Ready check for the task needs to check if we can swap garden still.

**Comment by horrible-little-slime** [comment]
That's not how gardens work

**Comment by ianknowles** [comment]
right my bad thought I had it figured out. Its visiting the garden while tall grass is planted with no growth and trying to fight mushrooms.

**Comment by ianknowles** [comment]
checking for garden growth in the ready check? might be whats needed

**Comment by Rinn** [comment]
i am unsure how that would happen, this logic is unchanged as far as I can see and it uses the packet of mushroom spores before trying to adventure there

**Comment by Rinn** [comment]
please make an issue and tag me

**Comment by ianknowles** [comment]
Made an issue, but yeah its just when you don't have Robort, familiar is undefined. Upgrading to new mafia with the new JS error handling made it easy to track.

**Pull request merged**
