### PR TITLE
free goofballs

### PR DESCRIPTION
**Pull request by Rinn**

### CODE REVIEW

**Comment by horrible-little-slime** [comment]
Does this work in CS aftercore? is there a more precise check we can apply here than "is the woods unlocked"?

**Comment by s-k-z** [comment]
I think checking if `questL03Rat` is not unstarted is a decent way to check. That should guarantee you have access to the tavern.

**Comment by Rinn** [comment]
I'll check today

**Comment by Rinn** [comment]
Yeah you're right, no tavern access in cs aftercore this needs to check questL03Rat

**Pull request merged**
