### PR TITLE
Ask for Ode to Booze buff when without skill

### PR DESCRIPTION
**Pull request by eegeeZA**
Allow those without Ode to Booze to request it from the generous Buffy bot.

### CODE REVIEW

**Review by s-k-z — CHANGES_REQUESTED** [review]
Please switch it to one of the other buffbots. Buffy is an altruistic service provided free of charge which is best left for newer players and those not automating the game.

**Comment by Malibu-Stacey** [comment]
I am vehemently against this.
I suggest you try playing the game for a change instead of spending 17 years meatfarming.

**Comment by eegeeZA** [comment]
@s-k-z I'll do some research and then revert with the changes.

@Malibu-Stacey I can understand your stance, but I do believe different people play the game differently. The intent behind this change is not break the way you play the game but to introduce an alternative style for others.

**Comment by eegeeZA** [comment]
@s-k-z will `Flesh Puppet` be a reasonable alternative?

**Comment by gausie** [comment]
I think you need to make a proactive case for the changes you've made to mitigate the negative effect your change would have on the community.

**Comment by eegeeZA** [comment]
Okay sure. My account is 17 years old, and I've never ascended. I started playing more actively again since Crimbo last year, after quite a long hiatus. My class is a Seal Clubber, and I don't have access to Ode to Booze by any means, besides requesting buffs. Ascending now would mean having to lose 92 skills after perming one. I really enjoy using garbo for some meat farming.

If I understand the concern correctly, adding this change might discourage others from ascending? Or is it that making use of a buff bot as part of automation is frowned upon?

**Comment by s-k-z** [comment]
Personally I don't have strong opinions about paying for buffs through automation. Using a free service that consumes the resources of the provider is not acceptable, similar to how we don't automatically grab a carpe from the VIP Floundry. I believe Flesh Puppet is another free service, just like Buffy.

Discouraging others from ascending is another big issue, and we really don't want to promote that. Players who go deeper into that hole will essentially be trapped, as you may find yourself. Basically, we should always send the message that it is better to ascend sooner rather than later.

**Pull request closed without merging**
